#! /bin/bash

doIt () {
    while [ 1 ]
    do
        if [ "$(spotifycli --playbackstatus)" == "$(echo Playing)" ];
        then
            if [ "$(spotifycli --artist)" == "$(echo)" ];
            then
                spotifycli --mute
            else
                spotifycli --unmute
            fi
        fi
        sleep 1
    done
}

doIt &>/dev/null &
